"""Lesson content, ordered along the ML pipeline. Text supports **bold** and `code` (rendered by the UI)."""
from __future__ import annotations

LESSONS: list[dict] = [
    {
        "id": "missing", "order": 1, "stage": "Cleaning", "emoji": "🕳️", "title": "Missing values aren't random",
        "tagline": "Throwing away incomplete rows can quietly bias everything that follows.",
        "modeled_on": "Predicting a diabetic patient's return to the hospital (UCI · 130 US hospitals)",
        "learn": [
            {"icon": "🧩", "heading": "Real data has holes", "body": "Hospitals don't run every test on every patient, people skip survey questions, sensors drop out. Models can't do maths with a blank, so every blank needs a decision."},
            {"icon": "🗑️", "heading": "The tempting fix: drop the row", "body": "Deleting incomplete rows feels clean. But if **40%** of rows have *any* blank, you just threw away 40% of your evidence — and maybe not a random 40%."},
            {"icon": "🎯", "heading": "Missing for a reason", "body": "Doctors order the **HbA1c** blood test mostly for patients they're already worried about. So 'test missing' secretly means 'probably healthier'. Keep only complete rows and your training set becomes a ward of the sickest patients — a model trained there over-predicts readmission for everyone else."},
            {"icon": "🩹", "heading": "Fill in, don't throw out", "body": "**Imputation** fills each blank with a sensible stand-in — the median for numbers, the most common value for categories — and keeps every row. Tree models can even learn that 'exactly the median' often meant 'not measured'."},
        ],
        "demo": "missing",
        "demo_caption": "Toggle between dropping and filling blanks and watch how many patients survive — and how the readmission rate of the survivors shifts.",
        "quiz": [
            {"q": "Why can dropping rows with blanks make a model worse even if lots of rows remain?",
             "options": ["Fewer rows always means a worse model", "The rows that remain may be systematically different from the people you'll predict for", "Models need blanks to learn", "Dropping rows changes the target column's name"],
             "answer": 1, "explain": "If blanks depend on something meaningful (like how sick a patient is), the complete rows form a biased sample."},
            {"q": "A blood test is missing for 60% of patients, mostly the healthy ones. What's a reasonable first move?",
             "options": ["Delete the column and every row with a blank", "Fill blanks with the median and keep all rows", "Replace blanks with 999", "Only train on patients who had the test"],
             "answer": 1, "explain": "Median imputation keeps the whole population. (999 would be a wild fake value that distorts scales and linear models.)"},
        ],
        "challenge": {
            "title": "Readmission radar", "dataset_name": "Hospital records (practice)",
            "story": "A hospital wants to flag patients likely to be readmitted within 30 days. Your teammate set things up to **drop every row with a missing value**. The model looks fine on paper — until it meets real patients.",
            "task": "Train a model that keeps working on the full patient population.",
            "hints": ["Open **Prepare → Clean**. How is a missing number handled right now?", "Look at the Data step: which columns have blanks, and how many rows would survive if you dropped them?", "Switch missing numbers to **median** and train again."],
            "solution": "Median imputation keeps all ~3,000 patients instead of a biased ~600. Accuracy on the hidden population jumps from ≈60% to ≈73%.",
        },
    },
    {
        "id": "outliers", "order": 2, "stage": "Cleaning", "emoji": "📏", "title": "Outliers & skewed targets",
        "tagline": "A few impossible values can wreck a model — and skewed targets deserve a log.",
        "modeled_on": "Predicting used car prices (Craigslist cars & trucks)",
        "learn": [
            {"icon": "🤯", "heading": "Typos are data too", "body": "Listings at **$0**, **$1** or **$2,000,000,000** are fat-finger errors. One billion-dollar Corolla pulls a regression line so hard that every normal car is predicted wrong."},
            {"icon": "🔎", "heading": "Look before you model", "body": "A histogram of the target exposes it instantly: a sensible hump and a few absurd points miles away. Decide what's *physically possible* (a used car between $500 and $300k) and remove rows outside it — that's cleaning, not cheating."},
            {"icon": "📈", "heading": "Skewed targets", "body": "Prices, salaries and view counts are **skewed**: lots of small values, a long tail of big ones. Models struggle because errors on expensive items dominate. Predicting **log(price)** turns the long tail into a tidy bell and makes errors proportional."},
            {"icon": "⚖️", "heading": "But don't delete what's real", "body": "A genuine $250k Mercedes isn't an error. Remove impossible values; keep rare-but-real ones."},
        ],
        "demo": "outliers",
        "demo_caption": "Drag the outliers in and out and watch the fitted line. Then flip on the log scale to see the skew disappear.",
        "quiz": [
            {"q": "Your price histogram shows most cars between $3k–$60k and three at over $500 million. What do you do?",
             "options": ["Keep them — more data is better", "Remove rows with impossible prices before training", "Delete the price column", "Train only on the three expensive cars"],
             "answer": 1, "explain": "Values that can't be real are errors; removing them is legitimate cleaning."},
            {"q": "Why predict log(price) instead of price?",
             "options": ["It makes the model faster", "It turns a long-tailed target into a balanced one so errors are proportional", "Logs are required for regression", "It removes outliers automatically"],
             "answer": 1, "explain": "On a log scale a 10% miss on a cheap car counts as much as a 10% miss on an expensive one."},
        ],
        "challenge": {
            "title": "Fair price finder", "dataset_name": "Used cars (practice)",
            "story": "A used-car marketplace wants instant price estimates. About **4%** of the listings contain typos — free cars and billion-dollar hatchbacks. The current models' R² is a disaster.",
            "task": "Predict prices for real listings accurately.",
            "hints": ["On the **Data** step, look at the `price` histogram and its min/max.", "On **Prepare → Clean**, turn on the **target range filter** and keep only plausible prices (e.g. $500 – $300,000).", "Also set **Target transform → log(1+y)**; prices are skewed."],
            "solution": "Filtering impossible prices and predicting log(price) lifts R² on clean listings from hugely negative to ≈0.93.",
        },
    },
    {
        "id": "leakage", "order": 3, "stage": "Features", "emoji": "🔮", "title": "Data leakage: answers from the future",
        "tagline": "If a column is only known after the fact, your 99% accuracy is fake.",
        "modeled_on": "Can we predict flight delays? (Airline delay causes)",
        "learn": [
            {"icon": "⏳", "heading": "Ask: when is this known?", "body": "To predict a delay *before departure*, a model may only use what's known before departure: time, airline, weather forecast, airport traffic. Columns like **carrier_delay_min** are filled in *after* landing."},
            {"icon": "🎭", "heading": "The too-good-to-be-true score", "body": "If 'minutes of delay caused by the carrier' is in your data, the model just learns 'more than 0 → delayed'. Test accuracy hits 99% because the test rows carry the same future columns."},
            {"icon": "💥", "heading": "Then reality hits", "body": "In production those columns are **empty** — the flight hasn't happened yet. The model has never learned anything real and falls back to guessing."},
            {"icon": "🧪", "heading": "Leak detectors", "body": "Suspiciously perfect scores, one feature with almost all the importance, and column names like *result*, *final*, *after*, *delay_cause* are red flags. Drop anything not available at prediction time."},
        ],
        "demo": "leakage",
        "demo_caption": "Step along the flight timeline. Columns light up when they become known — try predicting at departure time with and without the leaky ones.",
        "quiz": [
            {"q": "You're predicting loan default at application time. Which column is leakage?",
             "options": ["Applicant income", "Number of missed payments during the loan", "Requested amount", "Years employed"],
             "answer": 1, "explain": "Missed payments only exist after the loan is running — they're part of the outcome."},
            {"q": "Your model scores 99.8% on the test set at its first try. What should you do first?",
             "options": ["Celebrate and deploy", "Check which features it relies on and whether they'd be known at prediction time", "Add more models", "Lower the learning rate"],
             "answer": 1, "explain": "Near-perfect first scores are the classic symptom of leakage."},
        ],
        "challenge": {
            "title": "Departure board oracle", "dataset_name": "Flight delays (practice)",
            "story": "An airline app wants to warn travellers **at booking time** whether their flight will be delayed. The first model scored nearly 100% in testing… and then predicted 'on time' for every real flight.",
            "task": "Build a model that works when predicting *before* the flight.",
            "hints": ["Train once and open **Features**: is one group of columns doing all the work?", "Which columns would actually be known before take-off?", "On **Prepare → Clean**, ignore `carrier_delay_min`, `weather_delay_min` and `late_aircraft_min`."],
            "solution": "Without the three after-the-fact columns your test score drops from ~100% to ≈70% — but that's an honest 70% that holds up on real future flights (balanced accuracy ≈0.65 vs 0.50).",
        },
    },
    {
        "id": "scaling", "order": 4, "stage": "Preparation", "emoji": "📐", "title": "Feature scaling",
        "tagline": "When features live on different scales, distance-based models only see the big ones.",
        "modeled_on": "Predicting apartment prices in New York (NYC property sales)",
        "learn": [
            {"icon": "📏", "heading": "Meters vs rooms", "body": "Distance to the centre ranges from 200 to 25,000 metres. Rooms go from 1 to 5. To a model that measures distance between rows, a 1-room difference is invisible next to a 500 m difference."},
            {"icon": "👥", "heading": "Who's affected", "body": "**K-Nearest Neighbors**, **SVMs**, **linear models with regularization** and **neural networks** all care about scale. Tree models don't (they only ask 'is it bigger than X?')."},
            {"icon": "🎚️", "heading": "Standardize", "body": "**Standard scaling** subtracts each column's mean and divides by its spread, so every feature speaks the same language: 'how unusual is this value?'."},
            {"icon": "🔒", "heading": "Fit on training data only", "body": "The scaler learns its mean/spread from training rows and applies the same numbers to test rows — otherwise test information leaks into training."},
        ],
        "demo": "scaling",
        "demo_caption": "Pick an apartment and see which neighbours KNN thinks are 'closest' — before and after scaling.",
        "quiz": [
            {"q": "Which model is least affected by feature scaling?",
             "options": ["K-Nearest Neighbors", "Support Vector Machine", "Random Forest", "Neural network"],
             "answer": 2, "explain": "Trees split on thresholds of one feature at a time, so units don't matter."},
            {"q": "Why fit the scaler on training rows only?",
             "options": ["It's faster", "Using test rows would leak information about the test set into training", "Test rows can't be scaled", "It doesn't matter"],
             "answer": 1, "explain": "The test set must stay unseen — including its averages."},
        ],
        "challenge": {
            "title": "Neighbourhood know-how", "dataset_name": "Apartment rents (practice)",
            "story": "A rental site uses **K-Nearest Neighbors** to estimate rent from similar apartments. Somebody switched scaling off, and now 'similar' means 'similar distance from downtown and similar year built' — rooms barely count.",
            "task": "Get KNN to estimate rents accurately. (This challenge must be solved with **K-Nearest Neighbors**.)",
            "hints": ["Compare the ranges of `rooms` and `distance_to_center_m` on the Data step.", "On **Prepare → Scale**, what's selected?", "Choose **Standard** scaling and train KNN again."],
            "solution": "With standard scaling KNN's R² rises from ≈0.55 to ≈0.95 — the same model, just measuring distance fairly.",
        },
    },
    {
        "id": "imbalance", "order": 5, "stage": "Preparation", "emoji": "⚖️", "title": "Class imbalance & honest metrics",
        "tagline": "When 98% of cases are 'normal', accuracy tells you almost nothing.",
        "modeled_on": "Predicting fraudulent purchases (Credit card transactions)",
        "learn": [
            {"icon": "🎰", "heading": "The lazy 98% model", "body": "If only 2 in 100 transactions are fraud, a model that always says 'legit' is **98% accurate** — and catches zero fraud. Accuracy rewards ignoring the rare class."},
            {"icon": "🎯", "heading": "Precision & recall", "body": "**Recall**: of all real frauds, how many did we catch? **Precision**: of everything we flagged, how much was really fraud? A fraud team usually cares most about recall, as long as precision isn't absurd."},
            {"icon": "🧬", "heading": "Rebalance the training set", "body": "**Oversampling** (copies or **SMOTE**'s synthetic in-between points) grows the rare class; **undersampling** shrinks the common one; **class weights** make mistakes on the rare class cost more. Only the training rows change — the test stays real."},
            {"icon": "🎚️", "heading": "Thresholds", "body": "Models output a probability. Lowering the 50% cut-off flags more cases: more recall, less precision. It's a business decision, not a maths one."},
        ],
        "demo": "imbalance",
        "demo_caption": "Slide the fraud rate down and watch the 'always legit' model's accuracy stay high while its recall stays at zero.",
        "quiz": [
            {"q": "A model has 98% accuracy on data where 2% of rows are fraud. What do you know about it?",
             "options": ["It's excellent", "Nothing much — it might catch no fraud at all", "It has 98% recall", "It has 98% precision"],
             "answer": 1, "explain": "Always predicting 'legit' also scores 98%."},
            {"q": "Where should SMOTE be applied?",
             "options": ["To the whole dataset before splitting", "Only to the training rows", "Only to the test rows", "To the predictions"],
             "answer": 1, "explain": "Synthetic rows in the test set would make your score fiction."},
        ],
        "challenge": {
            "title": "Fraud catcher", "dataset_name": "Card transactions (practice)",
            "story": "Only **~2%** of card transactions are fraudulent. The current models look ~98% accurate, but the fraud team says they catch almost nothing.",
            "task": "Catch most of the fraud without flagging everyone.",
            "hints": ["After training, open **Errors**: how many frauds did the model actually catch?", "On **Prepare → Balance**, try **Grow the rare classes** with **SMOTE**.", "Logistic regression responds strongly to rebalancing; compare it with the forest."],
            "solution": "SMOTE oversampling lifts logistic regression's fraud recall from ≈14% to ≈75% while keeping precision above 10% — far more useful than 98% 'accuracy'.",
        },
    },
    {
        "id": "overfitting", "order": 6, "stage": "Modeling", "emoji": "🧠", "title": "Overfitting: memorising vs learning",
        "tagline": "A model that aces its homework can still fail the exam.",
        "modeled_on": "Predicting startup success (Startups dataset)",
        "learn": [
            {"icon": "📚", "heading": "Memorising the answer key", "body": "An unlimited decision tree can keep splitting until every training row sits in its own leaf: **100% training accuracy**. It learned the noise along with the pattern."},
            {"icon": "🧪", "heading": "The train–test gap", "body": "Compare training and test scores. A big gap means **overfitting**. Both low means **underfitting** (too simple)."},
            {"icon": "✂️", "heading": "Simplify on purpose", "body": "Limit **max depth**, require more **samples per leaf**, add **regularization**, drop useless features, or use early stopping for neural nets. Simpler models generalise better when data is small and noisy."},
            {"icon": "🔁", "heading": "Cross-validation", "body": "One test split can be lucky. **K-fold cross-validation** trains K times on different slices and averages — a steadier way to choose settings."},
        ],
        "demo": "overfitting",
        "demo_caption": "Turn up the model's complexity and watch training error fall while test error eventually climbs — the classic U-curve.",
        "quiz": [
            {"q": "Training accuracy 100%, test accuracy 68%. What's happening?",
             "options": ["Underfitting", "Overfitting", "Data leakage in the test set", "Perfect model"],
             "answer": 1, "explain": "A large gap between training and test performance is the signature of overfitting."},
            {"q": "Which change usually reduces a decision tree's overfitting?",
             "options": ["Increase max depth", "Decrease min samples per leaf", "Limit max depth / require more samples per leaf", "Add more noisy columns"],
             "answer": 2, "explain": "Both constrain how finely the tree can carve up the training data."},
        ],
        "challenge": {
            "title": "Unicorn detector", "dataset_name": "Startups (practice)",
            "story": "An investor has only **320 past startups**, a handful of meaningful facts and **40 noisy dashboard metrics**. Their unlimited decision tree is perfect on the past and unreliable on new pitches.",
            "task": "Make the decision tree generalise. (This challenge must be solved with a **Decision Tree**.)",
            "hints": ["Train, then compare **train vs test** accuracy on the leaderboard.", "Open the tree's settings (Models step) — what's the max depth?", "Try max depth 3–4 and at least 10–15 samples per leaf. Feature selection can help too."],
            "solution": "A depth-3 tree with ≥15 samples per leaf scores ≈79% on new startups versus ≈73% for the memorising tree.",
        },
    },
    {
        "id": "shortcut", "order": 7, "stage": "Generalization", "emoji": "🪤", "title": "Spurious shortcuts",
        "tagline": "Models love easy clues — even ones that only work by accident.",
        "modeled_on": "Predicting the probability of heart disease (BRFSS heart disease indicators)",
        "learn": [
            {"icon": "🏥", "heading": "How the data was collected", "body": "In this hospital network, patients with suspected heart disease were referred to the **Cardiology Centre**. So in the training data, 'clinic = Cardiology Centre' almost *means* 'sick'."},
            {"icon": "🐺", "heading": "The husky problem", "body": "A famous image model 'recognised' wolves by spotting **snow** in the background. Models grab whatever separates the labels most easily — causal or not."},
            {"icon": "🌍", "heading": "Deployment changes the rules", "body": "Roll the model out to a screening programme where everyone visits every clinic, and the shortcut stops working. The model never learned blood pressure, cholesterol or age."},
            {"icon": "🔍", "heading": "Catch it", "body": "Check **feature importance**: is one column dominating? Ask whether the relationship would still hold where the model will be used. If not, remove it and let the model learn the real signal."},
        ],
        "demo": "shortcut",
        "demo_caption": "Train on the referral hospital, then deploy to a new screening programme. Toggle whether the model may use the clinic.",
        "quiz": [
            {"q": "What makes a feature a 'spurious shortcut'?",
             "options": ["It has missing values", "It predicts the label in your data for a reason that won't hold where the model is used", "It's a categorical column", "It's measured after the outcome"],
             "answer": 1, "explain": "(Columns measured after the outcome are leakage — a related but different problem.)"},
            {"q": "One feature has 90% of the importance and it's 'which hospital the record came from'. Best next step?",
             "options": ["Celebrate the strong signal", "Ask whether that relationship holds in deployment; if not, drop it and retrain", "Add more hospitals as features", "Increase model depth"],
             "answer": 1, "explain": "Dominant 'context' features are often shortcuts."},
        ],
        "challenge": {
            "title": "Heart check, anywhere", "dataset_name": "Heart screening (practice)",
            "story": "A heart-disease screening model trained on records from a referral network will be rolled out to **community clinics** where the clinic says nothing about the diagnosis.",
            "task": "Build a model that still works after the roll-out.",
            "hints": ["Train once and look at **Features** — which column dominates?", "Would the clinic a patient visited predict their heart health in a community screening programme?", "Ignore `clinic` on **Prepare → Clean** and retrain."],
            "solution": "Without the clinic shortcut the model must learn age, blood pressure, cholesterol and lifestyle — balanced accuracy in the new setting rises from ≈0.54 to ≈0.73.",
        },
    },
    {
        "id": "fairness", "order": 8, "stage": "Responsible ML", "emoji": "🤝", "title": "Fairness & proxy bias",
        "tagline": "Removing the sensitive column isn't enough when another column gives it away.",
        "modeled_on": "Predicting loan repayment (Prosper loans) · and the recidivism fairness challenge",
        "learn": [
            {"icon": "📜", "heading": "History is in the labels", "body": "Our loan records come from years of biased bookkeeping: many women who repaid were recorded as defaults. A model trained on these labels learns 'female → risky' — repeating the injustice."},
            {"icon": "📊", "heading": "Measure per group", "body": "Overall accuracy can look fine while one group is treated far worse. Compare **approval rates for people who would actually repay** (true positive rate) between groups."},
            {"icon": "🕵️", "heading": "Proxies", "body": "Delete `gender` and the model may rediscover it through **proxies** — here `shopping_profile` correlates strongly with gender. Look for columns that reveal the sensitive attribute."},
            {"icon": "🛠️", "heading": "What helps", "body": "Remove the sensitive attribute **and** its strong proxies, audit per-group metrics, and question the labels. (Fairness has many definitions — choose one deliberately.)"},
        ],
        "demo": "fairness",
        "demo_caption": "Move the approval threshold and compare how often deserving applicants in each group get approved.",
        "quiz": [
            {"q": "You removed the `race` column but your model still treats groups differently. Why might that be?",
             "options": ["Removal didn't save", "Other columns (proxies) like zip code still reveal race", "Models ignore removed columns", "Fairness can't be measured"],
             "answer": 1, "explain": "Proxies carry the same information indirectly."},
            {"q": "Which metric directly checks whether deserving applicants are approved equally often across groups?",
             "options": ["Overall accuracy", "R²", "True positive rate per group", "Log loss"],
             "answer": 2, "explain": "Equal opportunity compares true positive rates between groups."},
        ],
        "challenge": {
            "title": "Fair lending", "dataset_name": "Loan applications (practice)",
            "story": "A lender wants to automate approvals using historical outcomes — but the history under-recorded women's repayments. Regulators will audit approval rates for applicants **who truly repay**, split by gender.",
            "task": "Approve good applicants accurately **and** equally across genders.",
            "hints": ["What does the model learn from `gender`? Try ignoring it — then check the gap again.", "Is another column standing in for gender? Look at `shopping_profile` per gender on the Data step.", "Ignore both `gender` and `shopping_profile`, then train again."],
            "solution": "Dropping gender alone still leaves a ≈25-point gap via the shopping-profile proxy. Dropping both shrinks the gap to ≈1–3 points while accuracy on true outcomes *improves* (≈0.70).",
        },
    },
]

LESSON_INDEX = {l["id"]: l for l in LESSONS}

NEW_LESSONS = {
    "baselines": {
        "id": "baselines", "stage": "Framing", "emoji": "🎯", "title": "Baselines: is 0.82 any good?",
        "tagline": "A score means nothing until you compare it with the dumbest possible model.",
        "modeled_on": "Predicting how long a bus will be delayed (NYC late buses)",
        "learn": [
            {"icon": "🤷", "heading": "Numbers without context", "body": "\"R² = 0.12\" or \"91% accurate\" sound like facts, but you can't judge them alone. Is 91% great? Not if 90% of buses are on time anyway."},
            {"icon": "🎯", "heading": "The baseline", "body": "A **baseline** is the laziest model imaginable: always predict the **average** (regression) or the **most common class** (classification). Every training run in this app adds one automatically — look for the 🎯 row."},
            {"icon": "📏", "heading": "Beat it by how much?", "body": "Compare errors: if the baseline is off by 6.0 minutes on average and your model by 5.4, you only improved **10%**. A useful model usually beats the baseline clearly."},
            {"icon": "🔁", "heading": "When you barely beat it", "body": "The model may be the wrong shape (a straight line can't follow a rush-hour hump), important features may be missing, or the target may simply not be predictable from these columns."},
        ],
        "demo": "baselines",
        "demo_caption": "Switch between always-the-average, a straight line and a smarter curve, and watch how much each one actually beats the baseline.",
        "quiz": [
            {"q": "90% of transactions are legitimate. A model is 92% accurate. What's the honest summary?",
             "options": ["Excellent model", "Only slightly better than always saying 'legitimate'", "92% recall", "It can't be judged at all"],
             "answer": 1, "explain": "The 'always legitimate' baseline already scores 90%."},
            {"q": "What's a sensible baseline for predicting house prices?",
             "options": ["A neural network", "Always predicting the average price", "Random numbers", "The most expensive house"],
             "answer": 1, "explain": "The mean (or median) is the classic regression baseline."},
        ],
        "challenge": {
            "title": "Rush-hour realist", "dataset_name": "Bus delays (practice)",
            "story": "A transit app wants to show expected delay. The team's straight-line model reports an R² above zero and they're ready to ship — but compared with simply showing the average delay, is it actually helping riders?",
            "task": "Build a model that clearly beats the always-the-average baseline.",
            "hints": ["Train and find the 🎯 baseline row on the leaderboard. How far ahead is the linear model?", "Delays peak twice a day — can a straight line through `hour` capture two humps?", "Try a tree-based model (Random Forest, XGBoost), or engineer a rush-hour feature."],
            "solution": "The straight line beats the baseline by only ≈9%. A random forest that can follow the two rush-hour peaks beats it by ≈53%.",
        },
    },
    "features": {
        "id": "features", "stage": "Features", "emoji": "🛠️", "title": "Feature engineering",
        "tagline": "Good features beat fancy models.",
        "modeled_on": "Predicting tips on New York taxi rides from trip data",
        "learn": [
            {"icon": "👓", "heading": "Models only see your columns", "body": "A model can't invent information. If tips depend on **fare × paying by card**, a linear model given only `fare` and `paid_by_card` separately can't express it."},
            {"icon": "📅", "heading": "Dates are gold — once unpacked", "body": "A timestamp like `2025-03-14 23:10` is useless raw. Split it into **hour**, **weekday**, **month** and patterns like 'late night' appear."},
            {"icon": "➗", "heading": "Ratios, products, buckets", "body": "**Price per m²**, **fare × card**, **age buckets** — combining columns the way the real world works often helps more than switching algorithms."},
            {"icon": "🧮", "heading": "Formulas", "body": "The **Formula** tool lets you write your own feature, e.g. `paid_by_card * (hour >= 22)`. Engineered features are re-computed automatically when the saved model predicts on new data."},
        ],
        "demo": "features",
        "demo_caption": "Give a linear model better features one at a time and watch its fit — and R² — jump.",
        "quiz": [
            {"q": "Tips are about 20% of the fare, but only for card payments. Which feature helps a linear model most?",
             "options": ["fare + paid_by_card", "fare × paid_by_card", "passengers", "trip ID"],
             "answer": 1, "explain": "The product is exactly 'fare when paid by card' — the pattern itself."},
            {"q": "Why split a timestamp into parts like hour and weekday?",
             "options": ["Dates use too much memory", "Models can't learn patterns from a raw date string, but can from its parts", "It removes leakage", "It's required by law"],
             "answer": 1, "explain": "Hour-of-day and weekday are where daily and weekly patterns live."},
        ],
        "challenge": {
            "title": "Tip whisperer", "dataset_name": "Taxi rides (practice)",
            "story": "A taxi company wants to estimate tips with a **simple, explainable linear model**. Right now it explains about 70% of the variation. Card riders tip a share of the fare, cash tips are never recorded, and late-night riders are more generous.",
            "task": "Reach R² ≥ 0.93 on new rides — using a **linear model** (linear, ridge, lasso or elastic net).",
            "hints": ["On **Prepare → Create features**, split `pickup_time` into its hour.", "Add a **product** feature: `fare × paid_by_card`.", "Add a **formula**: `paid_by_card * ((pickup_time_hour >= 22) or (pickup_time_hour < 4))` for the late-night bonus."],
            "solution": "Date parts alone don't help a linear model (R² ≈0.72). With `fare × card` and a card-late-night flag it reaches ≈0.96 — same model, better features.",
        },
    },
    "splits": {
        "id": "splits", "stage": "Preparation", "emoji": "✂️", "title": "Honest splits: groups & time",
        "tagline": "If the test set shares patients — or the future — with training, your score is a memory test.",
        "modeled_on": "Predicting Alzheimer's from medical data (repeated clinic visits)",
        "learn": [
            {"icon": "👥", "heading": "Rows aren't always independent", "body": "One patient visits 5 times. Their visits look alike — same quirks, same measurements. A random split puts some visits in training and others in test."},
            {"icon": "🧠", "heading": "Then the test cheats", "body": "The model recognises the *patient*, not the disease. Your test score says 90%; on brand-new patients it drops. The score was **measuring memory**."},
            {"icon": "🧱", "heading": "Group split", "body": "Keep **every row of a group on one side** (all visits of a patient, all transactions of a customer). Now the test really asks: 'does this work on someone new?'"},
            {"icon": "⏩", "heading": "Time split", "body": "For anything that changes over time — sales, prices, demand — train on the **past** and test on the **future**. A random split lets the model peek at tomorrow. Also remove **exact duplicates**: copies in both sets are free answers."},
        ],
        "demo": "splits",
        "demo_caption": "Split patients randomly or as whole groups, and compare what the test score promises with what new patients get.",
        "quiz": [
            {"q": "Each customer has ~20 transactions. Which split gives an honest estimate for new customers?",
             "options": ["Random rows", "Keep each customer's rows together (group split)", "Sort by amount", "Use all rows for training"],
             "answer": 1, "explain": "Otherwise the model meets the same customers in training and test."},
            {"q": "You're forecasting next month's sales. How should you split?",
             "options": ["Randomly", "Train on earlier months, test on the latest months", "Test on the oldest months", "No test set needed"],
             "answer": 1, "explain": "That mirrors real use: predicting a future you haven't seen."},
        ],
        "challenge": {
            "title": "New-patient promise", "dataset_name": "Memory clinic visits (practice)",
            "story": "A memory clinic will use your model for **new patients**. Each training patient visited 3–7 times. Your colleague split the rows randomly and reported a great score — the clinic wants a model *and* a test score they can trust.",
            "task": "Train a good model whose own test score honestly predicts how it does on new patients (within 3.5 points).",
            "hints": ["Look at `patient_id` on the Data step — how many rows per patient?", "On **Prepare → Split**, choose **Keep groups together** and pick `patient_id`.", "Compare your new test score with the old one — which one would you tell the clinic?"],
            "solution": "With a random split the test score overstates new-patient accuracy by ≈10 points. A group split by patient gives an estimate within ≈1 point of reality.",
        },
    },
    "calibration": {
        "id": "calibration", "stage": "Evaluation", "emoji": "🌡️", "title": "Trusting probabilities: calibration & error analysis",
        "tagline": "When a model says 30%, does it happen 30% of the time?",
        "modeled_on": "Will a patient need intensive care after surgery?",
        "learn": [
            {"icon": "🛏️", "heading": "Probabilities get used", "body": "A hospital adds up predicted ICU probabilities to decide **how many beds** to prepare. If the model says 30% but only 10% of such patients need ICU, beds sit empty and staff are wasted."},
            {"icon": "📈", "heading": "Calibration curves", "body": "Group predictions into bins (0–10%, 10–20%…) and compare the average prediction with what actually happened. A **calibrated** model lies on the diagonal. **Calibration error** (ECE) is the average gap."},
            {"icon": "⚠️", "heading": "Rebalancing distorts probabilities", "body": "SMOTE and oversampling teach the model that the rare class is common, so every probability is inflated. Great for catching cases — bad for trustworthy probabilities. Calibrating on the *rebalanced* rows doesn't fix it: it keeps the fake base rate."},
            {"icon": "🔬", "heading": "Error analysis", "body": "Don't stop at one number. Look at the **most confident mistakes** and at **slices** — accuracy per procedure, age group or region — to find where the model fails. The **Mistakes** and **Calibration** tabs show both."},
        ],
        "demo": "calibration",
        "demo_caption": "Turn up oversampling and watch the calibration curve bend — and the number of beds you'd prepare drift away from reality.",
        "quiz": [
            {"q": "Patients given a 40% ICU risk end up in ICU 15% of the time. The model is…",
             "options": ["Perfectly calibrated", "Over-confident (probabilities too high)", "Under-confident", "Leaking"],
             "answer": 1, "explain": "Predictions are higher than observed frequencies."},
            {"q": "You need accurate probabilities but oversampled the rare class. What's the cleanest fix?",
             "options": ["Oversample more", "Train on the real class mix (turn oversampling off), then calibrate if needed", "Calibrate on the oversampled training rows", "Ignore it"],
             "answer": 1, "explain": "Calibration needs data with the real base rate."},
        ],
        "challenge": {
            "title": "Bed planner", "dataset_name": "Surgery outcomes (practice)",
            "story": "About **12%** of surgery patients need intensive care. Someone 'fixed the imbalance' with SMOTE, and now the hospital prepares far too many ICU beds — the probabilities are inflated.",
            "task": "Give the hospital probabilities it can plan with (calibration error ≤ 3%) while still ranking patients well (ROC-AUC ≥ 0.75).",
            "hints": ["Train, then open the **Calibration** tab: where does the curve sit relative to the diagonal?", "What did rebalancing do to the base rate the model believes in?", "Turn **Prepare → Balance** back to *None* (and optionally calibrate probabilities in Train options)."],
            "solution": "With SMOTE, logistic regression's calibration error is ≈28%. Trained on the real class mix it drops to ≈1% — same ranking ability (AUC ≈0.81). Calibrating on SMOTE rows alone stays at ≈28%.",
        },
    },
}

NEW_LESSONS.update({
    "convolutions": {
        "id": "convolutions", "stage": "Vision", "emoji": "🔍", "title": "Convolutions: seeing shapes anywhere",
        "tagline": "Treat a picture as a table of pixels and the model can't recognise a shape that moved.",
        "modeled_on": "Galaxy morphology classification (SDSS) — shapes stand in for galaxy types",
        "learn": [
            {"icon": "🔢", "heading": "A picture is a grid of numbers", "body": "A 32×32 colour image is 3,072 numbers. A classic model like logistic regression or a random forest treats each one as a separate column: 'pixel 517 is bright'."},
            {"icon": "📍", "heading": "Pixels-as-a-table can't generalise position", "body": "If a star appeared top-left during training, pixel-based models learn 'stars light up the top-left pixels'. Show them a star at the bottom-right and they've never seen those pixels light up."},
            {"icon": "🔦", "heading": "Convolutions slide a pattern detector", "body": "A **convolution filter** is a tiny 3×3 pattern (an edge, a corner, a colour blob) that slides over the whole image and lights up wherever it matches. The *same* detector works everywhere — that's **weight sharing**."},
            {"icon": "🧱", "heading": "Stacking layers", "body": "Early filters find edges, later ones combine them into corners and points, and **global average pooling** asks 'did this pattern appear anywhere?' — so the network recognises a star wherever it is."},
        ],
        "demo": "convolutions",
        "demo_caption": "Slide a filter across the picture and watch where it lights up — then move the shape and compare a pixel model with a convolution.",
        "quiz": [
            {"q": "Why does a logistic regression on raw pixels struggle when objects move around the image?",
             "options": ["It's too slow", "Each pixel is a separate feature, so a shape in a new place lights up pixels it never learned about", "It can't handle colour", "It needs more classes"],
             "answer": 1, "explain": "Pixel models tie what they learn to exact positions."},
            {"q": "What makes a convolution layer work at any position?",
             "options": ["It has a weight per pixel", "The same small filter is applied across the whole image (weight sharing)", "It uses decision trees", "It removes colour"],
             "answer": 1, "explain": "One detector, slid everywhere."},
        ],
        "challenge": {
            "title": "Shape spotter", "dataset_name": "Shapes anywhere (practice)",
            "story": "A telescope team sorts objects by shape. Their models treat each image as 3,072 independent pixel columns — and they barely beat guessing because the shapes show up anywhere in the frame.",
            "task": "Classify shapes in new images with at least 70% accuracy.",
            "hints": ["Train once: how do the 'pixels as a table' models do compared with the 25% baseline?", "Which model in the gallery is built for pictures?", "Add the **Image CNN** (or Tiny ResNet) on the Models step and train again."],
            "solution": "Logistic regression and random forests stay near 24–38%. A CNN with global average pooling recognises the shapes anywhere: ≈90%.",
        },
    },
    "augmentation": {
        "id": "augmentation", "stage": "Vision", "emoji": "🔄", "title": "Data augmentation",
        "tagline": "Teach the model what doesn't change the answer.",
        "modeled_on": "Image classification with limited, tidy training photos",
        "learn": [
            {"icon": "📸", "heading": "Training photos are too tidy", "body": "All training shapes are **centred and upright**. Real photos aren't: things are off-centre, rotated, darker or partly hidden."},
            {"icon": "🤔", "heading": "The model only knows what it saw", "body": "A CNN trained on upright squares has never seen a square standing on its corner. To it, a rotated square may look like a new shape."},
            {"icon": "🔄", "heading": "Augmentation", "body": "While training, randomly **rotate, shift, flip, brighten or cut out** parts of each image. The label stays the same, so the model learns that these changes *don't matter*. It's free extra data."},
            {"icon": "⚠️", "heading": "Only label-preserving changes", "body": "Flipping a cat is fine; flipping an arrow pointing left makes it point right — a different label! Pick augmentations that keep the answer the same. Augmentation applies to neural nets during training only."},
        ],
        "demo": "augmentation",
        "demo_caption": "Turn augmentations on and watch one training photo multiply into many variations — and see how a model trained with them handles rotated shapes.",
        "quiz": [
            {"q": "Your digit classifier is trained on centred digits but users upload off-centre ones. What helps?",
             "options": ["Fewer epochs", "Random shift augmentation during training", "Grayscale", "A bigger test set"],
             "answer": 1, "explain": "Shifting during training teaches position doesn't matter."},
            {"q": "Which augmentation would be WRONG for classifying left vs right arrows?",
             "options": ["Brightness", "Small shifts", "Horizontal flips", "Cutout"],
             "answer": 2, "explain": "A horizontal flip turns a left arrow into a right arrow — it changes the label."},
        ],
        "challenge": {
            "title": "Shapes in the wild", "dataset_name": "Tidy shapes (practice)",
            "story": "Every training photo shows a shape **centred and upright**. In the field, shapes appear anywhere and at any angle — and the current CNN gets confused.",
            "task": "Train a model that recognises shapes at any position and angle (≥ 80% on real-world photos).",
            "hints": ["Look at the training gallery on the Images step — what do all the photos have in common?", "On **Prepare → Augmentation**, add random rotation and shift.", "Try rotation up to 180° and shift around 30%, then train the CNN again."],
            "solution": "Without augmentation the CNN reaches ≈66% on shifted, rotated shapes. With rotation + shift augmentation it reaches ≈85–94% — same data, same model.",
        },
    },
})

NEW_LESSONS.update({
    "choosing_k": {
        "id": "choosing_k", "stage": "Discover", "emoji": "🫧", "title": "Clustering: how many groups?",
        "tagline": "Clustering always finds the number of groups you ask for — so ask carefully.",
        "modeled_on": "Retail world — customer segmentation (clustering)",
        "learn": [
            {"icon": "🧩", "heading": "No answers to learn from", "body": "In **clustering** there's no target column. The algorithm groups rows that look alike — useful for customer segments, document topics, or machine states."},
            {"icon": "🎯", "heading": "K-means needs a k", "body": "K-means drops **k** centres, assigns each row to the nearest one, moves each centre to the middle of its rows, and repeats until nothing moves. It will happily split your data into 3 groups even if there are really 5."},
            {"icon": "📉", "heading": "Choosing k", "body": "Try several k and compare: the **silhouette** score (how much closer points are to their own group than to the next one — higher is better) and the **elbow** of the within-group spread (inertia). Pick a k where the groups are crisp *and* make sense."},
            {"icon": "🔍", "heading": "Name the groups", "body": "A cluster is only useful once you can describe it: 'young, frequent, discount-loving' → *students*. The cluster **profiles** show which features make each group different."},
        ],
        "demo": "choosing_k",
        "demo_caption": "Change k and watch k-means move its centres, while the silhouette and the elbow tell you which k fits.",
        "quiz": [
            {"q": "You run k-means with k=3 on data that truly has 5 groups. What happens?",
             "options": ["It refuses to run", "It merges some real groups into 3 clusters", "It finds 5 anyway", "It labels the rest as noise"],
             "answer": 1, "explain": "K-means always returns exactly k groups."},
            {"q": "Which signal helps choose k?",
             "options": ["The silhouette score across different k", "Training accuracy", "ROC-AUC", "The number of columns"],
             "answer": 0, "explain": "Silhouette (and the elbow) compare how well-separated the groups are for each k."},
        ],
        "challenge": {
            "title": "Segment the shoppers", "dataset_name": "Shoppers (practice)",
            "story": "A retailer wants customer segments for marketing. The analyst ran k-means with the default **k = 3** and the segments feel muddled — the marketing team can't describe them.",
            "task": "Find segments that match the real customer types (a hidden column checks your groups — agreement ARI ≥ 0.85).",
            "hints": ["Train once and look at the cluster profiles — do any clusters look like two kinds of shoppers mixed together?", "Open **Refine → k sweep** and compare silhouette for k = 2…10.", "Set K-Means to the k with the best silhouette and train again."],
            "solution": "With k = 3 real segments get merged (ARI ≈ 0.57). The k sweep peaks at k = 5, which recovers the five shopper types almost perfectly (ARI ≈ 1.0).",
        },
    },
    "curse": {
        "id": "curse", "stage": "Discover", "emoji": "🌫️", "title": "The curse of dimensionality",
        "tagline": "With enough noisy columns, every point looks equally far from every other.",
        "modeled_on": "Predicting suspicious network packets (many weak features)",
        "learn": [
            {"icon": "📏", "heading": "Distances need signal", "body": "Clustering, KNN and anomaly detection all compare **distances**. A useful column adds real differences; a noisy column adds random ones."},
            {"icon": "🌫️", "heading": "Noise piles up", "body": "With 3 meaningful sensors and 40 noisy ones, the random part of every distance dwarfs the real part. Groups that are obvious in 3-D become invisible in 43-D — the **curse of dimensionality**."},
            {"icon": "🧮", "heading": "PCA finds the strong directions", "body": "**PCA** rotates the data to the directions of greatest variation. When useful sensors move *together*, they form a direction that stands far above the noise. Keep only the components that stand out on the **scree plot** and drop the rest."},
            {"icon": "✂️", "heading": "Fewer, better dimensions", "body": "Reducing dimensions (PCA, feature selection, domain knowledge) often helps clustering and distance-based models more than any tuning."},
        ],
        "demo": "curse",
        "demo_caption": "Add noisy columns one by one and watch the gap between near and far neighbours vanish — then let PCA find the signal again.",
        "quiz": [
            {"q": "Why does adding many noisy columns hurt k-means?",
             "options": ["It makes training slower only", "Random differences dominate the distances, hiding real groups", "K-means can't handle more than 10 columns", "It changes k"],
             "answer": 1, "explain": "Distances get swamped by noise."},
            {"q": "On a PCA scree plot, one component explains far more than the rest, which sit at a flat level. What should you keep?",
             "options": ["All components", "Just the component(s) that stand out above the flat noise level", "Only the last component", "None"],
             "answer": 1, "explain": "The flat tail is noise; the standout components carry the signal."},
        ],
        "challenge": {
            "title": "Machine moods", "dataset_name": "Factory sensors (practice)",
            "story": "A factory logs **43 sensor channels**. Engineers know the machines run in four states, but k-means on all channels produces meaningless groups. Somewhere in the noise, a few sensors tell the real story.",
            "task": "Recover the four machine states (agreement with the hidden states ARI ≥ 0.75).",
            "hints": ["Train once: how well do the clusters match? Look at the profiles — do they make sense?", "On **Prepare → Reduce**, add a PCA step. Train a PCA 'map' model first to see its scree plot.", "Keep only the components that stand out on the scree plot (here: 1) and cluster again with k = 4."],
            "solution": "On all 43 channels k-means scores ARI ≈ 0.31. PCA reveals one direction far above the noise; clustering on it recovers the four states (ARI ≈ 0.98).",
        },
    },
})

NEW_LESSONS.update({
    "bag_of_words": {
        "id": "bag_of_words", "stage": "Language", "emoji": "💬", "title": "Bag of words: when order matters",
        "tagline": "Count words and 'not good' looks exactly like 'good'.",
        "modeled_on": "Classifying a song's / review's sentiment from its text",
        "learn": [
            {"icon": "🧺", "heading": "Text as a bag of words", "body": "The simplest way to turn text into numbers: count which words appear (**TF-IDF** also down-weights common words like 'the'). Each word becomes a column."},
            {"icon": "🙃", "heading": "Order gets lost", "body": "In a bag of words, 'the battery is **not good**' and 'the battery is good, **not** bad' contain the same kinds of words. A linear model adds up word weights, so it can't learn that *not* flips the meaning of the word after it."},
            {"icon": "🔗", "heading": "N-grams keep a little order", "body": "Adding **bigrams** — pairs of neighbouring words like 'not good' — gives the model a column for the phrase itself. Suddenly negation is easy."},
            {"icon": "🧠", "heading": "Neural networks read context", "body": "A **GRU** reads words in order and remembers what came before; a **Transformer** lets every word attend to every other. Both can learn negation without hand-made phrases."},
        ],
        "demo": "bag_of_words",
        "demo_caption": "Type a review and watch a bag-of-words model and a phrase-aware model disagree when you add 'not'.",
        "quiz": [
            {"q": "Why does a linear unigram (single-word) model struggle with 'not good'?",
             "options": ["It doesn't know the word 'good'", "Each word gets one weight, so 'not' can't flip the meaning of 'good'", "It's too slow", "It needs images"],
             "answer": 1, "explain": "Word weights simply add up; there's no interaction between 'not' and 'good'."},
            {"q": "What's the cheapest fix that keeps a simple linear model?",
             "options": ["Remove the word 'not'", "Add bigrams (two-word phrases) as features", "Lowercase the text", "Use fewer words"],
             "answer": 1, "explain": "'not good' becomes its own feature."},
        ],
        "challenge": {
            "title": "Review reader", "dataset_name": "Product reviews (practice)",
            "story": "An online shop sorts reviews into positive and negative. A third of the reviews use **negation** — 'not great', 'not bad at all' — and the current word-counting models get confused.",
            "task": "Classify new reviews with at least 90% accuracy.",
            "hints": ["Train and open the mistakes: what do the misclassified reviews have in common?", "On **Prepare → Words**, switch from single words to **words + pairs (bigrams)**.", "Or add a model that reads in order — the GRU or the Tiny Transformer."],
            "solution": "Single-word models plateau around 64% because 'not good' and 'good' share their words. With bigrams a plain logistic regression reaches ≈100%; a GRU or Transformer gets there by reading in order.",
        },
    },
})

NEW_LESSONS.update({
    "popularity_bias": {
        "id": "popularity_bias", "stage": "Recommend", "emoji": "🔥", "title": "Popularity bias",
        "tagline": "Recommending the hits looks safe — and buries everything else.",
        "modeled_on": "Movie ratings / recommendation projects (MovieLens-style)",
        "learn": [
            {"icon": "📋", "heading": "The top-10 list", "body": "A recommender ranks items for each person; we judge it by how many of the things they later liked appear in their **top 10** (**recall@10**)."},
            {"icon": "🔥", "heading": "Popularity is a strong baseline", "body": "Recommending the most-liked items to everyone is simple and not terrible — blockbusters are popular for a reason."},
            {"icon": "🕳️", "heading": "…but it starves the long tail", "body": "Everyone gets the same list, so most of the catalogue is never shown (**coverage**). Niche films that a particular viewer would love never surface, and their creators never get discovered."},
            {"icon": "🧲", "heading": "Personalise", "body": "**Item-kNN** recommends neighbours of what *you* liked ('people who liked this also liked…'); **matrix factorisation** learns taste vectors. Both spread attention across the catalogue while finding more of what each person actually likes."},
        ],
        "demo": "popularity_bias",
        "demo_caption": "Slide between 'everyone gets the hits' and 'fully personal' and watch recall and catalogue coverage trade places.",
        "quiz": [
            {"q": "What does a low coverage score mean?",
             "options": ["Recommendations are slow", "Only a small part of the catalogue is ever recommended", "Users rated few items", "The model overfits"],
             "answer": 1, "explain": "Coverage = share of items that appear in anyone's recommendations."},
            {"q": "Why is popularity a good baseline but a poor final recommender?",
             "options": ["It can't be computed", "It ignores each person's taste and hides niche items", "It needs a GPU", "It only works for movies"],
             "answer": 1, "explain": "It's the same list for everybody."},
        ],
        "challenge": {
            "title": "Beyond the blockbusters", "dataset_name": "Movie ratings (practice)",
            "story": "A streaming service shows everyone the same 'Top picks' — the most popular films. Viewers find a few hits, but 90% of the catalogue is never shown.",
            "task": "Recommend films viewers go on to like (recall@10 ≥ 22%) while showing at least 40% of the catalogue.",
            "hints": ["Train and compare recall@10 and coverage on the leaderboard.", "Add a personal model on the Models step — 'Similar items' or 'Similar people'.", "Train again and check both goals."],
            "solution": "Popularity finds ≈13% of what viewers liked next while covering 10% of films. Item-kNN finds ≈30% and covers ≈54% of the catalogue.",
        },
    },
    "cold_start": {
        "id": "cold_start", "stage": "Recommend", "emoji": "🧊", "title": "Cold start",
        "tagline": "A brand-new user has told you almost nothing. Now what?",
        "modeled_on": "Recommendation systems for new users (MovieLens-style)",
        "learn": [
            {"icon": "🆕", "heading": "New users have no history", "body": "Collaborative filtering learns from what you rated. A newcomer with two ratings gives the model almost nothing to go on — the **cold-start problem**."},
            {"icon": "🧩", "heading": "Factor models struggle most", "body": "Matrix factorisation must estimate a whole taste vector from two numbers. With so little evidence it guesses wildly."},
            {"icon": "🛟", "heading": "Fallbacks and neighbours", "body": "Common fixes: show **popular items** until a user has rated a handful (a hybrid), or use **item-kNN**, which works directly from 'items similar to the two you liked'."},
            {"icon": "🔁", "heading": "Then hand over", "body": "As ratings arrive, switch to the personal model. Many products also ask newcomers to pick favourites during sign-up for exactly this reason."},
        ],
        "demo": "cold_start",
        "demo_caption": "Give a new user 0, 1, 2… ratings and watch how each recommender's list improves — and when the popularity fallback should step aside.",
        "quiz": [
            {"q": "Why does matrix factorisation do badly for a user with 2 ratings?",
             "options": ["It deletes new users", "It must estimate a full taste vector from almost no data", "It only recommends popular items", "It needs timestamps"],
             "answer": 1, "explain": "Two ratings can't pin down many taste dimensions."},
            {"q": "A common cold-start fix is…",
             "options": ["Recommend nothing", "Fall back to popular items until the user has rated a few", "Retrain every second", "Use a bigger model"],
             "answer": 1, "explain": "A hybrid that trusts the personal model only once it has enough ratings."},
        ],
        "challenge": {
            "title": "Welcome, newcomer", "dataset_name": "Movie ratings (practice)",
            "story": "The service uses matrix factorisation. It works for regulars, but **300 new viewers** have rated just two films each — and their recommendations are poor.",
            "task": "Recommend well for brand-new viewers who've rated only 2 films (recall@10 ≥ 12%).",
            "hints": ["The hidden test is all newcomers — what does the factor model know about them?", "Open the matrix factorisation settings: there's a **new-user fallback**.", "Or try 'Similar items', which works from the two films they liked."],
            "solution": "Matrix factorisation alone finds ≈7.5% of what newcomers like. A popularity fallback for users with fewer than 5 ratings (≈18%) or item-kNN (≈19%) more than doubles it.",
        },
    },
})

NEW_LESSONS.update({
    "no_peeking": {
        "id": "no_peeking", "stage": "Forecast", "emoji": "🔮", "title": "No peeking at the future",
        "tagline": "A forecast can only use what you'd actually know on the day you make it.",
        "modeled_on": "Store-sales forecasting (Rossmann-style), where the 'customers' column famously isn't known in advance",
        "learn": [
            {"icon": "⏳", "heading": "Forecasting is predicting the future", "body": "On Monday you forecast the next 4 weeks. You know everything up to Sunday — and **nothing** after. Any feature that sneaks in information from later is cheating."},
            {"icon": "🔀", "heading": "Random splits peek", "body": "Shuffle the rows and every test day sits between training days, scored one step ahead with the true recent values. Real forecasts run weeks ahead on their own guesses. Test on the **last stretch of time** instead."},
            {"icon": "🕵️", "heading": "Some columns only exist afterwards", "body": "Number of customers, the weekly total, the weather that *actually* happened: they're recorded once the day is over. A model that leans on them aces every test and falls apart on the real future, when they aren't known yet."},
            {"icon": "✅", "heading": "The honest setup", "body": "Use only columns you'd **know in advance** (planned promotions, holidays, a weather *forecast*), build features from the past (lags, rolling averages), and test with a **time split** so your score is a real multi-step forecast."},
        ],
        "demo": "no_peeking",
        "demo_caption": "Drag the 'today' line, toggle a leaky column and the split type, and watch your test score and the real-world score drift apart.",
        "quiz": [
            {"q": "Why does a random split flatter a forecasting model?",
             "options": ["It uses less data", "Test days sit between training days and are scored with true recent values", "It removes outliers", "It changes the units"],
             "answer": 1, "explain": "The model effectively interpolates instead of forecasting ahead."},
            {"q": "Which column can you safely use to forecast next month's sales?",
             "options": ["Number of customers each day", "Next month's planned promotion days", "The weekly sales total", "Tomorrow's actual temperature"],
             "answer": 1, "explain": "Promotions are planned in advance; the others are only known after the fact."},
        ],
        "challenge": {
            "title": "Four weeks ahead", "dataset_name": "Shop sales (practice)",
            "story": "A shop wants a 4-week sales forecast for staffing. The analyst's model scores brilliantly in testing — but the forecasts it sends each Monday are way off.",
            "task": "Forecast the next 28 days so the real-world error is at most 2× your own test error, with real-world MASE ≤ 1.2.",
            "hints": ["Train and compare your test score with what you'd expect — does it look too good?", "On **Prepare**, look at the extra columns: which one is only known after the day is over?", "Untick **customers**, switch the split to **Last stretch of time**, and train again."],
            "solution": "With `customers` the model is off by 3–6× more in the real future than its test promised (real MASE ≈ 1.5–2). Without it, and with a time split, the test is honest (ratio ≈ 1.1) and MASE ≈ 0.6–0.9.",
        },
    },
})

ORDER = ["baselines", "missing", "outliers", "leakage", "features", "splits", "scaling", "imbalance", "overfitting",
         "calibration", "shortcut", "fairness", "choosing_k", "curse", "bag_of_words", "popularity_bias", "cold_start",
         "convolutions", "augmentation"]
_by_id = {l["id"]: l for l in LESSONS} | NEW_LESSONS
LESSONS = [{**_by_id[i], "order": n + 1} for n, i in enumerate(ORDER)]
LESSON_INDEX = {l["id"]: l for l in LESSONS}
